wifi: ath11k: Fix fortify-string build error
The following build error is seen when using gcc 13.x:

In function ‘strlcpy’,
    inlined from ‘ath11k_coredump_build’ at drivers/net/wireless/ath
/ath11k/coredump.c:37:2,
    inlined from ‘ath11k_coredump_submit’ at drivers/net/wireless/ath
/ath11k/coredump.c:93:9,
    inlined from ‘ath11k_mhi_pm_rddm_worker’ at drivers/net/wireless/ath
/ath11k/coredump.c:151:2:
./include/linux/fortify-string.h:255:25:
error: call to ‘__write_overflow’ declared with attribute error: detected
write beyond size of object (1st parameter)
  255 |                         __write_overflow();
      |                         ^~~~~~~~~~~~~~~~~~

Change strlcpy function and use strscpy fixes this issue since this function
doesn't overflow, and add a NUL terminator and the don’t do a strlen(src).

Fixes: 2b6930915102 ("[FROM-QUECTEL] wifi: ath11k: add helper dumping function")
Signed-off-by: Rogerio Alves <rogerio.cardoso@collabora.com>